### ISSUE TITLE
[BUG] - Unable to click in the dialog box after selecting chat.

### ISSUE THREAD

**Issue by rustyorb** [mnikonov/gpt-labs#19]
### Description
After entering API KEY and ORG ID, and creating a chat with the info and select it. I can't interact with the chat input area. Like is greyed out. I installed the certificate, and both side loaded and through the app store. I was however able to install on a different pc just fine. I am assuming I am missing some kind of dependency.. I may have Edge blocked, is edge required?

The app is awesome though, shocked you don't have more interest.

**Comment by mnikonov** [comment]
The application doesn't need Edge. And latest installer installs all dependencies. The application just was released - it in initial stage, so some issues possible... I'm working on app when have a free time :) 

The issue that you have described I haven't seen yet. Can you also post several images for a future investigation
