### ISSUE TITLE
[QUESTION] - support for GPT-4, (plus plugin support)

### ISSUE THREAD

**Issue by rfbeck** [mnikonov/gpt-labs#29]
This app is cool, it's good to access GPT from my desktop! But I assume it's using GPT-3 turbo. Since I am an Open AI plus user, can't I have access to GPT-4? And this app with plugin support would knock it out of the park.

**Comment by mnikonov** [comment]
OpenAI has two different subscriptions one for Chat GPT another for API. Chat GPT subscription has fixed monthly billing and API subscription has per request Billing.  

App itself has no limits regarding which models to use, it loads list of all available models according your OpenAI subscription. 
Probably, for API, you have trial subscription plan, that's limited with GTP-3.

You can check your profile to figureout that

1. [Billing](https://platform.openai.com/account/billing/overview)
2. [Usage](https://platform.openai.com/account/usage)
3. [Rate limits](https://platform.openai.com/account/rate-limits)

**Plugins** cool feature, but I haven't  check whether OpenAI exposes api for them... If 'yes' will try to integrate

P.S As for now I'm also have free subscription plan and it looks like per api requests billing is less expensive than ChatGPT, during 2 month usage of it cost me only 3.5$

**Comment by mnikonov** [comment]
New update regarding GTP 4 and API...

GPT-4 is currently in a limited beta and only accessible to those who have been granted access. Please [join the waitlist](https://openai.com/waitlist/gpt-4) to get access when capacity is available.

The information was taken from [ community forum ](https://community.openai.com/t/when-i-try-the-gpt-4-model-chat-completion-in-api-request-i-get-an-error-that-model-does-not-exist/98850)

**Comment by mnikonov** [comment]
App now supports latest models from Open AI
